version: 3
services:
    nginx:
        image: nginx
        container_name: mynginx
        volumes: 
            - ./conf.d/:/etc/nginx/conf.d/:rw
            - ./log:/var/log/nginx
            - ./www:/usr/share/nginx/html/:rw
        ports: 
            - "8080:8080"
        command: ["nginx", "-g", "daemon off;"]